In [1]:
import numpy as np

In [25]:
###Mój pierwszy wektor

In [5]:
x = np.array([1,2,3,4,5])

In [6]:
x.ndim

1

In [7]:
x.shape

(5,)

In [8]:
A = np.array([[1,2,3],[4,4,6],[1,1,1]])

In [9]:
A.shape

(3, 3)

In [10]:
A.ndim

2

In [14]:
A.shape = (2,3)

ValueError: total size of new array must be unchanged

In [17]:
A.reshape(1,9)

array([[1, 2, 3, 4, 4, 6, 1, 1, 1]])

In [23]:
A.reshape(3,-1)

array([[1, 2, 3],
       [4, 4, 6],
       [1, 1, 1]])

In [31]:
np.linspace(0,1,8)

array([ 0.        ,  0.14285714,  0.28571429,  0.42857143,  0.57142857,
        0.71428571,  0.85714286,  1.        ])

In [32]:

np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [35]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [36]:
np.zeros([2,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [37]:
np.empty([7,4])

array([[  6.93914533e-310,   8.94329174e-317,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          6.93914174e-310],
       [  6.93914172e-310,   6.93914173e-310,   6.93914478e-310,
          6.93914616e-310]])

In [38]:
np.ones([12,13])

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [44]:
np.random.uniform(-4, 4,(2,3))

array([[-2.35488525,  3.0142501 , -2.12143119],
       [ 1.20116483, -2.1780282 , -0.06860154]])

In [47]:
np.random.normal(100,15,(5,4))

array([[ 109.66009059,   95.45871042,  109.77390211,  102.42315354],
       [ 111.20440203,  103.54193364,  114.6819173 ,  120.17812741],
       [ 100.9938457 ,  113.24887813,   83.08802462,   91.91709463],
       [  84.18860786,  130.96422797,  110.30290742,  119.07241985],
       [  98.34062443,  119.82192001,   99.54504399,  105.68461244]])

In [48]:
np.random.randint(2,10,(3,3))

array([[5, 3, 6],
       [7, 2, 6],
       [2, 4, 9]])